FROM node:20-alpine

WORKDIR /app/frontend

ENV NODE_ENV=development \
	CHOKIDAR_USEPOLLING=true

COPY package*.json ./
RUN npm config set strict-ssl false && npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
